---
- name: wordpress 
  tags: wordpress
  hosts: all
  # become: true
  gather_facts: false
  tasks:
    - name: 'wp user get'
      command: "wp user get {{ user_name }} --field=display_name"
      args:
        chdir: /clients/www.oln.ca/current/webroot/
      register: task_result
      tags: wp_cli
    - name: 'Print output'
      debug: result='{{ task_result.stdout }}'
