---
- name: wordpress 
  tags: wordpress
  hosts: all
  # become: true
  gather_facts: false
  tasks:
    - name: 'wp plugin'
      command: "wp plugin {{ subcommand }} --format=json"
      args:
        chdir: /clients/www.oln.ca/current/webroot/
      register: task_result
      tags: wp_cli
    - name: 'Print output'
      debug: msg='{{ task_result.stdout }}'
