---
- name: wordpress 
  tags: wordpress
  hosts: all
  # become: true
  gather_facts: false
  tasks:
    - name: 'wp user get'
      command: "wp user get {{ user_name }} --fields=ID,display_name,user_email,user_registered --format=csv"
      args:
        chdir: /clients/www.oln.ca/current/webroot/
      register: task_result
      tags: wp_cli
    - name: 'Print output'
      debug: msg='{{ task_result.stdout }}'
